# Generated by Django 3.2 on 2021-05-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='z',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
    ]
