# Generated by Django 3.2 on 2021-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participant_result_survey_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='signal_decision_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='result',
            name='signal_id',
            field=models.IntegerField(blank=True),
        ),
    ]
