# Generated by Django 3.2 on 2021-05-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210504_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey_result',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
