# Generated by Django 3.2 on 2021-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210504_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
