# Generated by Django 3.2 on 2021-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210504_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='game_time',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
        migrations.AlterField(
            model_name='participant',
            name='instructions_time',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
        migrations.AlterField(
            model_name='participant',
            name='training_time',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
        migrations.AlterField(
            model_name='result',
            name='buy_info_decision_time',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
        migrations.AlterField(
            model_name='result',
            name='signal_decision_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11),
        ),
    ]
