# Generated by Django 3.2 on 2021-05-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='training_round',
            field=models.IntegerField(default=1),
        ),
    ]
