# Generated by Django 3.2 on 2021-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_participant_training_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='got_signal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='signal_decision_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='signal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
