from django.db import models
from django_countries.fields import CountryField


class Entry(models.Model):
    id = models.AutoField(primary_key=True)
    x = models.IntegerField()
    y = models.IntegerField()
    w = models.IntegerField()
    z = models.DecimalField(max_digits=11, decimal_places=6)
    voi = models.DecimalField(max_digits=11, decimal_places=6)
    s = models.IntegerField()
    v11 = models.IntegerField()
    v12 = models.IntegerField()
    v13 = models.IntegerField()
    v14 = models.IntegerField()
    v15 = models.IntegerField()
    v16 = models.IntegerField()
    v17 = models.IntegerField()
    v21 = models.IntegerField()
    v22 = models.IntegerField()
    v23 = models.IntegerField()
    v24 = models.IntegerField()
    v25 = models.IntegerField()
    v26 = models.IntegerField()
    v27 = models.IntegerField()
    v31 = models.IntegerField()
    v32 = models.IntegerField()
    v33 = models.IntegerField()
    v34 = models.IntegerField()
    v35 = models.IntegerField()
    v36 = models.IntegerField()
    v37 = models.IntegerField()
    v41 = models.IntegerField()
    v42 = models.IntegerField()
    v43 = models.IntegerField()
    v44 = models.IntegerField()
    v45 = models.IntegerField()
    v46 = models.IntegerField()
    v47 = models.IntegerField()
    v51 = models.IntegerField()
    v52 = models.IntegerField()
    v53 = models.IntegerField()
    v54 = models.IntegerField()
    v55 = models.IntegerField()
    v56 = models.IntegerField()
    v57 = models.IntegerField()
    n1 = models.IntegerField()
    n2 = models.IntegerField()
    n3 = models.IntegerField()
    n4 = models.IntegerField()
    n5 = models.IntegerField()
    n6 = models.IntegerField()
    n7 = models.IntegerField()
    n8 = models.IntegerField()
    n1_with = models.DecimalField(max_digits=11, decimal_places=6)
    n2_with = models.DecimalField(max_digits=11, decimal_places=6)
    n3_with = models.DecimalField(max_digits=11, decimal_places=6)
    n4_with = models.DecimalField(max_digits=11, decimal_places=6)
    n5_with = models.DecimalField(max_digits=11, decimal_places=6)
    n6_with = models.DecimalField(max_digits=11, decimal_places=6)
    n7_with = models.DecimalField(max_digits=11, decimal_places=6)
    n8_with = models.DecimalField(max_digits=11, decimal_places=6)
    n1_without = models.DecimalField(max_digits=11, decimal_places=6)
    n2_without = models.DecimalField(max_digits=11, decimal_places=6)
    n3_without = models.DecimalField(max_digits=11, decimal_places=6)
    n4_without = models.DecimalField(max_digits=11, decimal_places=6)
    n5_without = models.DecimalField(max_digits=11, decimal_places=6)
    n6_without = models.DecimalField(max_digits=11, decimal_places=6)
    n7_without = models.DecimalField(max_digits=11, decimal_places=6)
    n8_without = models.DecimalField(max_digits=11, decimal_places=6)
    sold_with = models.DecimalField(max_digits=11, decimal_places=6)
    sold_without = models.DecimalField(max_digits=11, decimal_places=6)
    used_count = models.IntegerField()


class Participant(models.Model):
    gender_choices = (('Male', 'Male'), ('Female', 'Female'))
    education_choices = (('Some High School', 'Some High School'), ('High School', 'High School'),
                         ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"),
                         ("Ph.D. or higher", "Ph.D. or higher"))
    participant_id = models.AutoField(primary_key=True)
    age = models.IntegerField()
    gender = models.CharField(null=True, blank=False, max_length=6, choices=gender_choices)
    education = models.CharField(null=True, blank=False, max_length=25, choices=education_choices)
    nationality = CountryField()

    instructions_time = models.DecimalField(max_digits=11, decimal_places=6)
    training_time = models.DecimalField(max_digits=11, decimal_places=6)
    game_time = models.DecimalField(max_digits=11, decimal_places=6)

    bonus = models.DecimalField(max_digits=11, decimal_places=6)
    bonus_payed = models.BooleanField()

    HITId = models.CharField(default=None, max_length=32)
    AssignmentId = models.CharField(max_length=32)

    round_pass_instructions = models.IntegerField(default=1)
    instructions_score = models.IntegerField(default=0)
    training_round = models.IntegerField(default=1)
    game_round = models.IntegerField(default=1)


class Result(models.Model):
    id = models.AutoField(primary_key=True)
    user_points = models.DecimalField(max_digits=12, decimal_places=5)
    agent_points = models.DecimalField(max_digits=12, decimal_places=5)
    bought_information = models.BooleanField()
    buy_info_decision_time = models.DecimalField(max_digits=11, decimal_places=6)
    round_num = models.IntegerField()
    training_question = models.BooleanField()
    worker_id = models.ForeignKey(Participant, on_delete=models.CASCADE)
    entry_id = models.ForeignKey(Entry, on_delete=models.CASCADE)
    got_signal = models.BooleanField(blank=True, null=True)
    signal_decision_time = models.DecimalField(max_digits=11, decimal_places=6, blank=True, null=True)
    signal_id = models.IntegerField(blank=True, null=True)


class Survey_result(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.CharField(max_length=200)
    answer = models.CharField(max_length=500)
    worker_id = models.ForeignKey(Participant, on_delete=models.CASCADE)
